name: Publish to DockerHub with a verstion-tag and latest-tag
on:    
  release:
      types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry with version-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/xteve-lazystream
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
    - name: Publish to Registry with latest-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/xteve-lazystream
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"